import React, { useEffect, useState } from 'react';
import { Table } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import request from '../components/dashboard/request';

export const TableList = ({ dataInfo, searchTime }: any) => {
  const columns: ColumnsType<any> = [
    {
      title: '项目名称',
      dataIndex: 'projectname',
      width: 150,
    },
    {
      title: '阶段名称',
      dataIndex: 'stagename',
      width: 150,
    },
    {
      title: '任务名称',
      dataIndex: 'name',
      width: 150,
    },
    {
      title: '开始时间',
      dataIndex: 'estStarted',
      width: 150,
    },
    {
      title: '计划结束时间',
      dataIndex: 'deadline',
      width: 150,
    },
    {
      title: '当前状态',
      dataIndex: 'status',
      width: 100,
    },
    {
      title: '当期进展（工时）',
      dataIndex: 'consumed',
      width: 160,
    },
    {
      title: '任务进展（%）',
      dataIndex: 'progress',
      render: val => `${(Number(val || 0) * 100).toFixed(2)}%`,
      width: 160,
    },
    {
      title: '描述',
      dataIndex: 'doc',
      width: 200,
    },
  ];
  const [data, setData] = useState<any[]>([]);
  useEffect(() => {
    const getDetail = async (project: string) => {
      try {
        let formData = new FormData();
        for (let key in searchTime) {
          formData.append(key, searchTime[key]);
        }
        formData.append('project', project);
        // const res = await request.post('/zzyDashboard-d1d3', formData);
        // setData(res?.data || []);
      } catch (error) {
        console.error(error);
        // setData([
        //   {
        //     id: '279',
        //     name: 'First type FDC DCP Modeling &amp; Verification(1 Type)',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '419',
        //     stagename: 'FDC Modeling',
        //     estimate: '100',
        //     curconsumed: '0',
        //     consumed: '100',
        //     estStarted: '2022-07-02',
        //     deadline: '2022-07-15',
        //     status: 'done',
        //     progress: '1',
        //     left: '0',
        //   },
        //   {
        //     id: '280',
        //     name: 'EDA DCP Modeling &amp; Verification',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '419',
        //     stagename: 'FDC Modeling',
        //     estimate: '1870',
        //     curconsumed: '0',
        //     consumed: '1870',
        //     estStarted: '2022-07-02',
        //     deadline: '2022-08-02',
        //     status: 'done',
        //     progress: '1',
        //     left: '0',
        //   },
        //   {
        //     id: '508',
        //     name: '\u9879\u76ee\u89c4\u5212',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '414',
        //     stagename: 'Preparation',
        //     estimate: '176',
        //     curconsumed: '0',
        //     consumed: '176',
        //     estStarted: '2021-06-15',
        //     deadline: '2021-07-15',
        //     status: 'done',
        //     progress: '1',
        //     left: '0',
        //   },
        //   {
        //     id: '509',
        //     name: 'PH1 FDC DCP Modeling &amp; Verification(9 Type)',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '419',
        //     stagename: 'FDC Modeling',
        //     estimate: '352',
        //     curconsumed: '0',
        //     consumed: '240',
        //     estStarted: '2022-07-01',
        //     deadline: '2022-08-31',
        //     status: 'done',
        //     progress: '1',
        //     left: '0',
        //   },
        //   {
        //     id: '510',
        //     name: 'PH2 FDC DCP Modeling &amp; Verification(75 Type)',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '419',
        //     stagename: 'FDC Modeling',
        //     estimate: '264',
        //     curconsumed: '0',
        //     consumed: '352',
        //     estStarted: '2022-08-01',
        //     deadline: '2022-09-30',
        //     status: 'done',
        //     progress: '1',
        //     left: '0',
        //   },
        //   {
        //     id: '511',
        //     name: 'FDC DCP Model Enhance',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '419',
        //     stagename: 'FDC Modeling',
        //     estimate: '1230',
        //     curconsumed: '24',
        //     consumed: '927',
        //     estStarted: '2022-08-01',
        //     deadline: '2023-02-28',
        //     status: 'doing',
        //     progress: '0.6341463414634146',
        //     left: '450',
        //   },
        //   {
        //     id: '512',
        //     name: 'PH3 FDC DCP Modeling &amp; Verification(35 Type)',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '419',
        //     stagename: 'FDC Modeling',
        //     estimate: '1055',
        //     curconsumed: '0',
        //     consumed: '94',
        //     estStarted: '2022-09-01',
        //     deadline: '2023-02-28',
        //     status: 'doing',
        //     progress: '0.11753554502369667',
        //     left: '931',
        //   },
        //   {
        //     id: '513',
        //     name: 'FDC/SPC Model Enhance',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '419',
        //     stagename: 'FDC Modeling',
        //     estimate: '1230',
        //     curconsumed: '40',
        //     consumed: '936',
        //     estStarted: '2022-09-01',
        //     deadline: '2023-03-31',
        //     status: 'doing',
        //     progress: '0.2569105691056911',
        //     left: '914',
        //   },
        //   {
        //     id: '514',
        //     name: 'FDC CIS Integration Testing',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '419',
        //     stagename: 'FDC Modeling',
        //     estimate: '80',
        //     curconsumed: '0',
        //     consumed: '72',
        //     estStarted: '2022-09-01',
        //     deadline: '2022-11-19',
        //     status: 'doing',
        //     progress: '0.7',
        //     left: '24',
        //   },
        //   {
        //     id: '515',
        //     name: 'FDC new requirement collection PH1',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '419',
        //     stagename: 'FDC Modeling',
        //     estimate: '56',
        //     curconsumed: '0',
        //     consumed: '56',
        //     estStarted: '2022-09-01',
        //     deadline: '2022-10-31',
        //     status: 'done',
        //     progress: '1',
        //     left: '0',
        //   },
        //   {
        //     id: '516',
        //     name: 'FDC new requirement collection PH2',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '419',
        //     stagename: 'FDC Modeling',
        //     estimate: '56',
        //     curconsumed: '0',
        //     consumed: '56',
        //     estStarted: '2022-10-01',
        //     deadline: '2022-11-30',
        //     status: 'done',
        //     progress: '1',
        //     left: '0',
        //   },
        //   {
        //     id: '517',
        //     name: 'FDC Basic Training',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '422',
        //     stagename: 'FDC Training for User',
        //     estimate: '3',
        //     curconsumed: '0',
        //     consumed: '3',
        //     estStarted: '2022-08-15',
        //     deadline: '2022-08-15',
        //     status: 'done',
        //     progress: '1',
        //     left: '0',
        //   },
        //   {
        //     id: '518',
        //     name: 'SECS DCP Training',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '422',
        //     stagename: 'FDC Training for User',
        //     estimate: '8',
        //     curconsumed: '0',
        //     consumed: '8',
        //     estStarted: '2022-09-01',
        //     deadline: '2022-09-01',
        //     status: 'done',
        //     progress: '1',
        //     left: '0',
        //   },
        //   {
        //     id: '519',
        //     name: 'EDA DCP Training',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '422',
        //     stagename: 'FDC Training for User',
        //     estimate: '8',
        //     curconsumed: '0',
        //     consumed: '8',
        //     estStarted: '2022-09-23',
        //     deadline: '2022-09-23',
        //     status: 'done',
        //     progress: '1',
        //     left: '0',
        //   },
        //   {
        //     id: '520',
        //     name: 'FDC&amp;SPC Modeling  Training',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '422',
        //     stagename: 'FDC Training for User',
        //     estimate: '8',
        //     curconsumed: '0',
        //     consumed: '8',
        //     estStarted: '2022-10-12',
        //     deadline: '2022-10-12',
        //     status: 'done',
        //     progress: '1',
        //     left: '0',
        //   },
        //   {
        //     id: '521',
        //     name: 'FDC SystemTraining',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '424',
        //     stagename: 'FDC Skill transfer for CIM',
        //     estimate: '29',
        //     curconsumed: '0',
        //     consumed: '0',
        //     estStarted: '2022-11-08',
        //     deadline: '2022-12-30',
        //     status: 'wait',
        //     progress: '0',
        //     left: '29',
        //   },
        //   {
        //     id: '522',
        //     name: ' Troubleshooting Training',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '424',
        //     stagename: 'FDC Skill transfer for CIM',
        //     estimate: '6',
        //     curconsumed: '0',
        //     consumed: '0',
        //     estStarted: '2023-01-03',
        //     deadline: '2023-02-28',
        //     status: 'wait',
        //     progress: '0',
        //     left: '6',
        //   },
        //   {
        //     id: '523',
        //     name: 'End User Training',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '421',
        //     stagename: 'APC Training for User',
        //     estimate: '140',
        //     curconsumed: '0',
        //     consumed: '69',
        //     estStarted: '2022-06-01',
        //     deadline: '2022-11-30',
        //     status: 'doing',
        //     progress: '0.5',
        //     left: '70',
        //   },
        //   {
        //     id: '524',
        //     name: 'CIM Training',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '423',
        //     stagename: 'APC Skill transfer for CIM',
        //     estimate: '352',
        //     curconsumed: '0',
        //     consumed: '2',
        //     estStarted: '2022-06-01',
        //     deadline: '2023-02-28',
        //     status: 'doing',
        //     progress: '-0.4943181818181819',
        //     left: '526',
        //   },
        //   {
        //     id: '525',
        //     name: 'APC Interface Development',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '420',
        //     stagename: 'ACP Modeling',
        //     estimate: '88',
        //     curconsumed: '0',
        //     consumed: '88',
        //     estStarted: '2021-08-03',
        //     deadline: '2021-09-30',
        //     status: 'done',
        //     progress: '1',
        //     left: '0',
        //   },
        //   {
        //     id: '526',
        //     name: 'APC Interface Test',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '420',
        //     stagename: 'ACP Modeling',
        //     estimate: '120',
        //     curconsumed: '0',
        //     consumed: '240',
        //     estStarted: '2021-10-12',
        //     deadline: '2021-10-29',
        //     status: 'done',
        //     progress: '1',
        //     left: '0',
        //   },
        //   {
        //     id: '527',
        //     name: 'APC Flow -  Requirement Collect PH1(LITHO)',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '420',
        //     stagename: 'ACP Modeling',
        //     estimate: '123',
        //     curconsumed: '0',
        //     consumed: '123',
        //     estStarted: '2021-08-03',
        //     deadline: '2021-10-29',
        //     status: 'done',
        //     progress: '1',
        //     left: '0',
        //   },
        //   {
        //     id: '528',
        //     name: 'APC Flow -  Requirement Collect PH1(CMP)',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '420',
        //     stagename: 'ACP Modeling',
        //     estimate: '120',
        //     curconsumed: '0',
        //     consumed: '240',
        //     estStarted: '2021-08-03',
        //     deadline: '2021-10-29',
        //     status: 'done',
        //     progress: '1',
        //     left: '0',
        //   },
        //   {
        //     id: '529',
        //     name: 'APC Flow -  Requirement Collect PH1(ETCH)',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '420',
        //     stagename: 'ACP Modeling',
        //     estimate: '120',
        //     curconsumed: '0',
        //     consumed: '120',
        //     estStarted: '2021-10-05',
        //     deadline: '2021-11-30',
        //     status: 'done',
        //     progress: '1',
        //     left: '0',
        //   },
        //   {
        //     id: '530',
        //     name: 'APC Flow -  Requirement Collect PH3(LITHO)',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '420',
        //     stagename: 'ACP Modeling',
        //     estimate: '220',
        //     curconsumed: '12',
        //     consumed: '192',
        //     estStarted: '2022-08-01',
        //     deadline: '2022-11-30',
        //     status: 'doing',
        //     progress: '0.09090909090909094',
        //     left: '200',
        //   },
        //   {
        //     id: '531',
        //     name: 'APC Flow -  Requirement Collect PH3(CMP)',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '420',
        //     stagename: 'ACP Modeling',
        //     estimate: '170',
        //     curconsumed: '12',
        //     consumed: '93',
        //     estStarted: '2022-10-11',
        //     deadline: '2022-11-30',
        //     status: 'doing',
        //     progress: '-1.3529411764705883',
        //     left: '400',
        //   },
        //   {
        //     id: '532',
        //     name: 'APC Flow -  Requirement Collect PH3(ETCH)',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '420',
        //     stagename: 'ACP Modeling',
        //     estimate: '170',
        //     curconsumed: '0',
        //     consumed: '85',
        //     estStarted: '2022-11-01',
        //     deadline: '2022-12-30',
        //     status: 'doing',
        //     progress: '-1',
        //     left: '340',
        //   },
        //   {
        //     id: '533',
        //     name: ' LITHO&amp;CMP&amp;ETCH PH3 Requirement Development',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '420',
        //     stagename: 'ACP Modeling',
        //     estimate: '350',
        //     curconsumed: '12',
        //     consumed: '148',
        //     estStarted: '2022-09-01',
        //     deadline: '2023-02-28',
        //     status: 'doing',
        //     progress: '-0.02857142857142847',
        //     left: '360',
        //   },
        //   {
        //     id: '534',
        //     name: 'APC Flow - APC Workflow &amp; UI Enhance',
        //     project: '413',
        //     projectname:
        //       '[BCDDT2021014-2A]ICRD-eFDC/eR2R Strategy Project(PD/CON)',
        //     stage: '420',
        //     stagename: 'ACP Modeling',
        //     estimate: '430',
        //     curconsumed: '28',
        //     consumed: '378',
        //     estStarted: '2022-09-01',
        //     deadline: '2023-02-28',
        //     status: 'doing',
        //     progress: '0.34883720930232553',
        //     left: '280',
        //   },
        // ]);
      }
    };
    if (dataInfo) {
      getDetail(dataInfo[0]?.id);
    }
  }, [searchTime, dataInfo]);

  return <Table columns={columns} dataSource={data} scroll={{ y: 280 }} />;
};
